### PR TITLE
Up minimum node version

### LINKED ISSUE #44: Tests don't succeed on version 0.7.2
Node version for testing: v10.6.0

```
sqlite-info-table
    ✓ should createInfoTable succeed
    ✓ should createInfoTable fails if info table already exists
    ✓ should return the number of keys in INFO_KEYS_LIST after setInfoKeys execution
    ✓ should return zero for an empty key after setInfoKey execution
    ✓ should return zero for an empty array after setInfoKey execution
    ✓ should return the keys in INFO_KEYS_LIST after setInfoKeys and getInfoKeys execution
    ✓ should return an empty array of keys after setInfoKeys and getInfoKeys execution

  sqlite-manager
    openDatabase
      ✓ should database open fail if none exists
      1) should database create succeed
      2) should create the data folder on database create (file mode)
      ✓ should create the data folder on database create (memory mode)
      3) should create and then open a database
      4) should create database -> create dataset -> close database -> open database -> return general schema
    createDataset
      5) "before each" hook: Create the dataset object for "should succeed if database empty"
    addData
      6) should return the number of elements added
      7) should add strings with double quotes
      ✓ should fail when adding duplicate unique index
      8) should succeed when adding non-duplicate unique index
      9) should warn when adding extra columns
    getDatasetData
      10) should return exactly the same element as inserted with non optimal search for object/array
      11) should return the limit number of elements
      12) should return with no limit and skip
      13) should return with limit and skip
      14) should order by ascending and descending
      15) should return data with projection on ndarray
      16) should return the same ndarray as written
      17) should return data with projection inclusion (random projection selection)
      18) should filter data [TBD]
      19) should return nqmMeta
      20) should work even when require cache is not used
    truncateResource
      21) should truncate the dataset and return the number of rows truncated
    getDatasetDataCount
      22) should should return the total count of rows satisfying a filter
    getResource
      ✓ should return the a resource for each database
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 49)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 51)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 53)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 58)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 61)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 62)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 63)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 65)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 66)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 67)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 68)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 69)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 71)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 72)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 73)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 74)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 75)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 76)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 77)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 79)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 81)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 82)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 83)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 84)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 85)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 87)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 88)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 89)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 90)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 91)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 92)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 93)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 94)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 95)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 96)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 97)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 98)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 99)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 100)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 101)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 102)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 103)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 104)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 105)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 106)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 107)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 108)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 109)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 110)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 111)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 112)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 113)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 114)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 115)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 116)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 117)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 118)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 119)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 120)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 121)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 122)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 123)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 124)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 125)
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 126)
      ✓ should return the name and description if they are defined
(node:7522) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
(node:7522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 127)
      ✓ should be rejected if the db is invalid
    updateData
      23) if throws is false, should return a CommandResult object on failure
      ✓ if throws is true, adding invalid data should cause an exception
      24) Adding invalid should fail but the next call should continue working
      25) if upsert is true, adding new primary key data should be like an insert
      26) if upsert is false, updating with new primary key data should do nothing
      27) Inserting data with the same unique index should update existing data
      28) Updating partial data should only update those fields
    deleteData
      29) should do nothing with no data
      30) should delete one data row
      31) should delete multiple data rows
      32) should error if deleting row without all primary keys defined
      33) deleting data should allow reinsertion
    updateDataByQuery
      34) should return zero count for an empty update object
      35) should update all entries for an empty query
      36) should not update any entry for a non valid query
      37) should update some entries for a non empty query
      38) should update some string entries for a non empty query
      39) should update some string entries for a non empty query
      ✓ should fail when updating a unique index with a duplicate value
      40) should succeed when updating a unique index with a non duplicate value
    getDistinct
      41) should return an empty list for an empty dataset
      42) should return early for an empty projection
      43) should return early for a false projection
      44) should return all keys for a present index
      45) should return list of distinct keys if there's no index present
      46) should return list of distinct keys for a given filter

  sqlite-ndarray
    ✓ should return a meta object for a ndarray object (row - order, 2D, Float64)
    ✓ should return a meta object for a ndarray object (row - order, 0D, Int8)
    ✓ should return a meta object for a ndarray object (column - order, 3D, Int8)
    ✓ should return the modified ndarray documents
    ✓ should write the ndarray documents to file (one per document)
    ✓ should write the ndarray documents to file (multiple per document)
    ✓ should read the ndarray documents from file (one per document)
    ✓ should read the ndarray documents from file (multiple per document)
    ✓ should read the same elemenst as written in ndarray documents (one per document)

  sqlite-schema-converter
    convertSchema
      ✓ should return empty for an empty input
      ✓ should return the converted schema for every element in tdx-schema-list


  26 passing (217ms)
  46 failing

  1) sqlite-manager
       openDatabase
         should database create succeed:
     Error: EEXIST: file already exists, mkdir '/home/alex/Projects/nqm-iot-database-utils/test/db'
  

  2) sqlite-manager
       openDatabase
         should create the data folder on database create (file mode):
     Error: EEXIST: file already exists, mkdir '/home/alex/Projects/nqm-iot-database-utils/test/db'
  

  3) sqlite-manager
       openDatabase
         should create and then open a database:
     Error: EEXIST: file already exists, mkdir '/home/alex/Projects/nqm-iot-database-utils/test/db'
  

  4) sqlite-manager
       openDatabase
         should create database -> create dataset -> close database -> open database -> return general schema:
     Error: EEXIST: file already exists, mkdir '/home/alex/Projects/nqm-iot-database-utils/test/db'
  

  5) sqlite-manager
       createDataset
         "before each" hook: Create the dataset object for "should succeed if database empty":
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  6) sqlite-manager
       addData
         should return the number of elements added:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  7) sqlite-manager
       addData
         should add strings with double quotes:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  8) sqlite-manager
       addData
         should succeed when adding non-duplicate unique index:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: EEXIST: file already exists, mkdir \'/tmp/nqm-iot-database-utils.d\''
  

  9) sqlite-manager
       addData
         should warn when adding extra columns:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  10) sqlite-manager
       getDatasetData
         should return exactly the same element as inserted with non optimal search for object/array:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  11) sqlite-manager
       getDatasetData
         should return the limit number of elements:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  12) sqlite-manager
       getDatasetData
         should return with no limit and skip:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  13) sqlite-manager
       getDatasetData
         should return with limit and skip:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  14) sqlite-manager
       getDatasetData
         should order by ascending and descending:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  15) sqlite-manager
       getDatasetData
         should return data with projection on ndarray:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  16) sqlite-manager
       getDatasetData
         should return the same ndarray as written:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  17) sqlite-manager
       getDatasetData
         should return data with projection inclusion (random projection selection):
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  18) sqlite-manager
       getDatasetData
         should filter data [TBD]:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  19) sqlite-manager
       getDatasetData
         should return nqmMeta:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  20) sqlite-manager
       getDatasetData
         should work even when require cache is not used:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  21) sqlite-manager
       truncateResource
         should truncate the dataset and return the number of rows truncated:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  22) sqlite-manager
       getDatasetDataCount
         should should return the total count of rows satisfying a filter:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  23) sqlite-manager
       updateData
         if throws is false, should return a CommandResult object on failure:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  24) sqlite-manager
       updateData
         Adding invalid should fail but the next call should continue working:
     TypeError: Cannot read property 'generalSchema' of undefined
      at Object.module.exports.manager.getGeneralSchema (lib/sqlite-manager.js:411:36)
      at Object.module.exports.manager.updateData (lib/sqlite-manager.js:757:34)
      at sqLiteManager.openDatabase.then.then.catch.then (test/test-sqlite-manager.js:1009:34)

  25) sqlite-manager
       updateData
         if upsert is true, adding new primary key data should be like an insert:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  26) sqlite-manager
       updateData
         if upsert is false, updating with new primary key data should do nothing:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  27) sqlite-manager
       updateData
         Inserting data with the same unique index should update existing data:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  28) sqlite-manager
       updateData
         Updating partial data should only update those fields:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  29) sqlite-manager
       deleteData
         should do nothing with no data:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  30) sqlite-manager
       deleteData
         should delete one data row:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  31) sqlite-manager
       deleteData
         should delete multiple data rows:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  32) sqlite-manager
       deleteData
         should error if deleting row without all primary keys defined:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  33) sqlite-manager
       deleteData
         deleting data should allow reinsertion:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  34) sqlite-manager
       updateDataByQuery
         should return zero count for an empty update object:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  35) sqlite-manager
       updateDataByQuery
         should update all entries for an empty query:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  36) sqlite-manager
       updateDataByQuery
         should not update any entry for a non valid query:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  37) sqlite-manager
       updateDataByQuery
         should update some entries for a non empty query:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  38) sqlite-manager
       updateDataByQuery
         should update some string entries for a non empty query:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  39) sqlite-manager
       updateDataByQuery
         should update some string entries for a non empty query:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  40) sqlite-manager
       updateDataByQuery
         should succeed when updating a unique index with a non duplicate value:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  41) sqlite-manager
       getDistinct
         should return an empty list for an empty dataset:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  42) sqlite-manager
       getDistinct
         should return early for an empty projection:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  43) sqlite-manager
       getDistinct
         should return early for a false projection:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  44) sqlite-manager
       getDistinct
         should return all keys for a present index:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  45) sqlite-manager
       getDistinct
         should return list of distinct keys if there's no index present:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  

  46) sqlite-manager
       getDistinct
         should return list of distinct keys for a given filter:
     Error: EEXIST: file already exists, mkdir '/tmp/nqm-iot-database-utils.d'
  



npm ERR! code ELIFECYCLE
npm ERR! errno 46
npm ERR! nqm-iot-database-utils@0.7.2 test: `mocha --no-warnings`
npm ERR! Exit status 46
npm ERR! 
npm ERR! Failed at the nqm-iot-database-utils@0.7.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2019-10-04T09_11_55_626Z-debug.log
```

### PR DESCRIPTION
**Pull request by aloisklink**
Fixes #44 

- Updates minimum Node version to `v10.12` (since we rely on `fs.mkdir`'s `recursive` flag, which only appears then)
- Adds Runtime Error if running an unsupported Node version.
- Updates ESLint rules
  - Refactors code to match ESLint rules
  - Removes the few files that use Anonymous closure module types with the project standard CommonJS module types.
    e.g. uses `module.exports.funcName = () => {};` instead of `module.exports = () => {return {funcName: () => {}};`

### CODE REVIEW

File: lib/sqlite-helper.js [hunk 1]
```diff
@@ -3,130 +3,122 @@
...
 
-module.exports = (function() {
-  "use strict";
-
-  const Promise = require("bluebird");
+/**
+ * @global
+ * @typedef {function} SQLiteStatementCreator
+ * @param {Array<string>} dataRowKeys - List of columns in the data.
+ *     This must be in the same order as the data will be binded.
```
Comment (IGlautier) [inline lib/sqlite-helper.js]: > as the data will be binded.

Is that a typo or am I missing something?

File: lib/sqlite-manager.js [hunk 2]
```diff
@@ -9,1031 +9,1017 @@
...
-   */
-  manager.closeDatabase = function(db) {
-    return new Promise((resolve, reject) => {
-      db.close((error) => {
+  // promisify the sqlite3.Database constructor
+  async function connectToDB() {
+    let db;
+    await new Promise((resolve, reject) => {
+      db = new sqlite3.Database(databasePath, databaseMode, (error) => {
         if (error) reject(error);
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: CURLY BRACES

File: lib/sqlite-helper.js (hunk 1 above)
Comment (aloisklink) [reply lib/sqlite-helper.js]: Ah, good shout, let me fix that.

It should be "as the data **that** will be _bound_."

File: lib/sqlite-manager.js [hunk 3]
```diff
@@ -9,1031 +9,1017 @@
...
+  options.schema = options.schema || {};
+
+  // Dataset data schema
+  options.schema.dataSchema = options.schema.dataSchema || {};
+
+  // Dataset primary key definition
+  options.schema.uniqueIndex = options.schema.uniqueIndex || [];
+
+  if (_.isEmpty(options.schema.dataSchema) && options.schema.uniqueIndex.length)
+    // throw early if there's a unique index but no schema
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: 2 lines with no curly braces :rage4:

File: lib/sqlite-manager.js [hunk 4]
```diff
@@ -9,1031 +9,1017 @@
...
+    return onlySchemaColumnRow;
+  });
+
+  // Get the ndarray keys
+  const ndarrayKeys = findCollectionKeys(
+    schema, sqliteConstants.SQLITE_GENERAL_TYPE_NDARRAY);
+
+  // Save the ndarray data to file
+  let arrayProcData = onlySchemaColumns;
+  if (ndarrayKeys. length > 0)
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: image

File: lib/sqlite-manager.js [hunk 5]
```diff
@@ -9,1031 +9,1017 @@
...
+ * @param {{string: number}} [options.sort]
+ *   Sorting object by schema keys:
+ *    e.g. `{prop1: 1, prop2: -1}`, where `1` = ascending, `-1` = descending.
+ * @param {boolean} [options.nqmMeta] - When set, the resource metadata will be returned along with the dataset
+ * data. Can be used to avoid a second call to `getResource`. Otherwise a URL to the metadata is provided.
+ * @return {Promise<DatasetData | any[]>}
+ */
+async function getDataQuery(db, distinct, filter, projection, options) {
+  // Set the default values
+  filter = filter || {};
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: Default args?

File: lib/sqlite-manager.js [hunk 6]
```diff
@@ -9,1031 +9,1017 @@
...
+ * @returns {Promise<CommandResult>} - Use the result property to check for
+ *     errors.
+ */
+module.exports.updateData = async function(db, data, upsert, throws) {
+  // See https://www.sqlite.org/lang_UPSERT.html for more info.
+
+  // setup default values
+  let set_upsert = upsert;
+  if (set_upsert === undefined) {
+    set_upsert = false;
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: Why set to false if you're throwing an error?

File: lib/sqlite-manager.js [hunk 7]
```diff
@@ -9,1031 +9,1017 @@
...
-    if (clauseIdx >= 0)
-      whereClause = ` ${sqliteCountTranslation.query.slice(clauseIdx)}`;
-
-    return new Promise((resolve, reject) => {
-      db.serialize(() => {
-        let result = {};
-
-        // Count the total number of rows in the dataset for a given query
-        db.get(
-          `SELECT Count(*) AS count FROM ${
```
Comment (IGlautier) [inline lib/sqlite-manager.js]: Ironic

Comment (IGlautier) [inline lib/sqlite-manager.js]: for (const key in keysToDisplayKeys) ?

File: lib/sqlite-helper.js [hunk 8]
```diff
@@ -3,130 +3,122 @@
...
-        Promise.all(promisedFinalizes).then((result) => {
-          // we resolve this massive promise when they all succeed
-          resolve(result);
-        }).catch((error) => {
-          reject(error);
-        });
+      } catch (error) {
+        reject(error);
+      } finally {
+        // very important that this runs
```
[the remark this answers is not in the document]
Comment (aloisklink) [reply lib/sqlite-helper.js]: Makes sense.

I usually try to keep within a 80-char line limit (due to constantly having to edit in vim over SSH/terminal), but in this case it fits on the same line.

File: lib/sqlite-manager.js (hunk 7 above)
Comment (aloisklink) [reply lib/sqlite-manager.js]: :stuck_out_tongue_closed_eyes:

File: lib/sqlite-manager.js (hunk 4 above)
Comment (aloisklink) [reply lib/sqlite-manager.js]: Added the eslint rule for this. Again surprised that `eslint:recommended` didn't already contain it.
Good catch!

File: lib/sqlite-manager.js (hunk 6 above)
Comment (aloisklink) [reply lib/sqlite-manager.js]: It was code I was going to add, then didn't get the time to.

I've deleted it, since it's just confusing until @mereacre or I do implement it.
